### ISSUE TITLE
Interface 'LaraLocker\LerningLocker\Statements\XAPIInterface' not found

### ISSUE THREAD

**Issue by djoudi** [ijeffro/laralocker#18]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Interface 'LaraLocker\LerningLocker\Statements\XAPIInterface' not found

in   \vendor\ijeffro\laralocker\src\LearningLocker\Statements\StatementHandler.php

**Comment by ijeffro** [comment]
Hey @djoudi are you still experiencing this issue?
