### ISSUE TITLE
"Class 'Ijeffro\Laralocker\AggregationHandler' not found"

### ISSUE THREAD

**Issue by djoudi** [ijeffro/laralocker#19]
"Class 'Ijeffro\Laralocker\AggregationHandler' not found"
in ijeffro\laralocker\src\LearningLocker.php

**Comment by ijeffro** [comment]
Hi @djoudi I am currently building the Aggregation handling, might take a couple of days :+1:

**Comment by ijeffro** [comment]
@djoudi if you want to contribute then please feel free.

**Comment by ijeffro** [comment]
Learning Locker Aggregation (Docs)[http://docs.learninglocker.net/http-aggregation/]
