### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Ijeffro\Laralocker\LearningLocker::connection()

### ISSUE THREAD

**Issue by djoudi** [ijeffro/laralocker#28]
![image](https://user-images.githubusercontent.com/152725/65615700-132ae480-dfba-11e9-9a79-d3f6cb9a20ac.png)

**Comment by djoudi** [comment]
@ijeffro

**Comment by ijeffro** [comment]
Sorry @djoudi - I will get this sorted pronto :+1:
